-- 公平价车型
CREATE TABLE QCM_CAR_MODELS2 (
  BRAND_ID          BIGINT      NULL, -- 品牌ID
  BRAND_NAME        VARCHAR(32) NULL, -- 品牌名称
  MODEL_ID          BIGINT      NULL, -- 型号ID
  MODEL_NAME        VARCHAR(32) NULL, -- 型号名称
  MANUFACTURER      VARCHAR(64) NULL, -- 生产厂商
  LEVEL             VARCHAR(32) NULL, -- 车辆级别
  VERSION_ID        BIGINT      NULL, -- 款型ID
  VERSION_NAME      VARCHAR(64) NULL, -- 款型名称
  OUTPUT_VOLUME     DOUBLE      NULL, -- 排量
  YEAR              INT         NULL, -- 年款
  NEW_CAR_PRICE     DOUBLE      NULL, -- 新车指导价
  GEAR_BOX          VARCHAR(32) NULL, -- 变速箱
  EFFLUENT_STANDARD VARCHAR(32) NULL, -- 排放标准
  FUEL_TYPE         VARCHAR(32) NULL -- 燃料类型
);

-- 参数
CREATE TABLE QCM_CAR_PARAMS (
  MODEL_ID    BIGINT      NULL, -- 车款ID
  MODEL_NAME  VARCHAR(64) NULL, -- 车款名称
  PARAM_TYPE  VARCHAR(64) NULL, -- 参数类型
  PARAM_NAME  VARCHAR(64) NULL, -- 参数名
  PARAM_VALUE VARCHAR(64) NULL -- 参数值
);

-- 店员用户
CREATE TABLE QCM_SHOP_USERS (
  USER_ID  BIGINT PRIMARY KEY    AUTO_INCREMENT, -- 用户ID
  USERNAME VARCHAR(32)  NOT NULL, -- 用户名
  SHOP_ID  BIGINT       NOT NULL, -- 4S店ID
  PASSWORD VARCHAR(128) NOT NULL, -- 密码
  CREDIT   INT          NOT NULL DEFAULT 0 -- 用户积分
);

CREATE INDEX IDX_QCM_SHOP_USERS_SHOP_ID ON QCM_SHOP_USERS (SHOP_ID);

CREATE UNIQUE INDEX UQ_IDX_QCM_SHOP_USERS_USERNAME ON QCM_SHOP_USERS (USERNAME);

-- 店员用户会话
CREATE TABLE QCM_SHOP_USER_SESSIONS (
  SESSION_ID   VARCHAR(128) PRIMARY KEY,
  USER_ID      BIGINT    NOT NULL,
  STATUS       BIT(1)    NOT NULL DEFAULT b'0',
  SIGN_IN_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX UQ_IDX_QCM_SHOP_USER_SESSIONS_USER_ID ON QCM_SHOP_USER_SESSIONS (USER_ID);

-- 汽车品牌
CREATE TABLE QCM_CAR_BRANDS (
  ID   BIGINT PRIMARY KEY, -- 品牌ID
  NAME VARCHAR(32) NOT NULL -- 品牌名称
);

-- 汽车型号
CREATE TABLE QCM_CAR_MODELS (
  ID           BIGINT PRIMARY KEY, -- 型号ID
  NAME         VARCHAR(32) NOT NULL, -- 型号名称
  BRAND_ID     BIGINT      NOT NULL, -- 所属品牌ID
  MANUFACTURER VARCHAR(64), -- 生产厂商
  LEVEL        VARCHAR(32) NULL -- 车辆级别
);

CREATE INDEX IDX_QCM_CAR_MODELS_BRAND_ID ON QCM_CAR_MODELS (BRAND_ID);

-- 汽车款号
CREATE TABLE QCM_CAR_VERSIONS (
  ID                BIGINT PRIMARY KEY, -- 款号ID
  NAME              VARCHAR(64) NOT NULL, -- 款号名称
  MODEL_ID          BIGINT      NOT NULL, -- 所属型号ID
  OUTPUT_VOLUME     DOUBLE      NULL, -- 排量
  YEAR              INT         NULL, -- 年款
  NEW_CAR_PRICE     DOUBLE      NULL, -- 新车指导价
  GEAR_BOX          VARCHAR(32) NULL, -- 变速箱
  EFFLUENT_STANDARD VARCHAR(32) NULL, -- 排放标准
  FUEL_TYPE         VARCHAR(32) NULL -- 燃料类型
);

CREATE INDEX IDX_QCM_CAR_VERSIONS_MODEL_ID ON QCM_CAR_VERSIONS (MODEL_ID);

-- API Admin用户
CREATE TABLE QCM_API_ADMINS (
  USERNAME VARCHAR(32) PRIMARY KEY,
  PASSWORD VARCHAR(128) NOT NULL,
  STATUS   BIT(1)       NOT NULL DEFAULT b'0'
);

-- 店员用户会话
CREATE TABLE QCM_API_ADMIN_SESSIONS (
  SESSION_ID    VARCHAR(128) PRIMARY KEY,
  USERNAME      VARCHAR(32) NOT NULL,
  STATUS        BIT(1)      NOT NULL DEFAULT b'0',
  TIMEOUT       BIGINT      NOT NULL DEFAULT 0,
  SIGN_IN_TIME  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SIGN_OUT_TIME TIMESTAMP   NULL
);

CREATE UNIQUE INDEX UQ_IDX_QCM_API_ADMIN_SESSIONS_USERNAME ON QCM_API_ADMIN_SESSIONS (USERNAME);

-- 汽车基本信息
CREATE TABLE QCM_CAR_BASIC_INFO (
  REG_ID         BIGINT PRIMARY KEY   AUTO_INCREMENT,
  CAR_ID         VARCHAR(32) NOT NULL,
  OWNER_NAME     VARCHAR(32) NOT NULL,
  OWNER_PHONE    VARCHAR(32) NULL,
  VERSION_ID     BIGINT      NOT NULL,
  MILEAGE        DOUBLE      NOT NULL,
  TRANSFER_TIMES INT         NOT NULL,
  REG_DATE       DATE        NOT NULL,
  STATUS         BIT(1)      NOT NULL DEFAULT b'0',
  CREATOR        BIGINT      NOT NULL,
  CREATE_TIME    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME    TIMESTAMP   NULL
);

CREATE UNIQUE INDEX UQ_IDX_QCM_CAR_BASIC_INFO_CAR_ID ON QCM_CAR_BASIC_INFO (CAR_ID);
CREATE INDEX IDX_QCM_CAR_BASIC_INFO_REG_DATE ON QCM_CAR_BASIC_INFO (REG_DATE);
CREATE INDEX IDX_QCM_CAR_BASIC_INFO_TRANSFER_TIMES ON QCM_CAR_BASIC_INFO (TRANSFER_TIMES);
CREATE INDEX IDX_QCM_CAR_BASIC_INFO_MILEAGE ON QCM_CAR_BASIC_INFO (MILEAGE);


-- 检测基本信息
CREATE TABLE QCM_CAR_DETECTION_INFO (
  REG_ID            BIGINT PRIMARY KEY,
  ACC_ELI_DETECT    TEXT      NULL, -- 事故排除检测
  APPEARANCE_DETECT TEXT      NULL, -- 外观检测
  INTERIOR_DETECT   TEXT      NULL, -- 内饰检测
  ELEC_EQP_DETECT   TEXT      NULL, -- 电气设备检测
  ENGINE_DETECT     TEXT      NULL, -- 发动机检测
  ROAD_TEST         TEXT      NULL, -- 路试检测
  EXP_PRICE         DOUBLE    NULL, -- 客户预期价格
  MIN_PRICE         DOUBLE    NULL, -- 公平价min * 1.05
  MAX_PRICE         DOUBLE    NULL, -- 公平价max * 1.05
  STATUS            BIT(1)    NOT NULL DEFAULT b'0',
  CREATOR           BIGINT    NOT NULL,
  CREATE_TIME       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME       TIMESTAMP NULL
);


-- 汽车图片
CREATE TABLE QCM_CAR_PHOTOS (
  ID           BIGINT PRIMARY KEY    AUTO_INCREMENT,
  REG_ID       BIGINT       NOT NULL,
  NAME         VARCHAR(64)  NOT NULL,
  STORAGE_NAME VARCHAR(128) NOT NULL,
  STATUS       BIT(1)       NOT NULL DEFAULT b'0',
  CREATOR      BIGINT       NOT NULL,
  CREATE_TIME  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME  TIMESTAMP    NULL
);

CREATE INDEX IDX_QCM_CAR_PHOTOS_REG_ID ON QCM_CAR_PHOTOS (REG_ID);

-- 审核结果
CREATE TABLE QCM_CAR_INFO_REVIEW (
  REG_ID      BIGINT PRIMARY KEY,
  PROCESS     ENUM('UNDER REVIEW', 'PASSED', 'REJECTED') NOT NULL DEFAULT 'UNDER REVIEW',
  MESSAGE     TEXT                                       NULL,
  INTEGRAL    INT                                        NULL, -- 积分
  AUDITOR     VARCHAR(32)                                NULL, -- 审计员(内部员工QCM_API_ADMINS)
  CREATE_TIME TIMESTAMP                                  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP                                  NULL
);

CREATE INDEX IDX_QCM_CAR_INFO_REVIEW_PROCESS ON QCM_CAR_INFO_REVIEW (PROCESS);

-- 实体店
CREATE TABLE QCM_SHOPS (
  ID                 BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME               VARCHAR(64)  NOT NULL,
  ADDRESS            VARCHAR(64)  NULL,
  BIZ_LICENSE_PIC    BIGINT       NULL,
  BIZ_LICENSE_REG_NO VARCHAR(64)  NULL,
  DESCRIPTION        VARCHAR(128) NULL,
  OWNER_ID           BIGINT       NOT NULL
);

CREATE INDEX IDX_QCM_SHOPS_OWNER_ID ON QCM_SHOPS (OWNER_ID);

-- 店主
CREATE TABLE QCM_SHOP_OWNERS (
  ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
  NICK_NAME    VARCHAR(32) NULL,
  ID_CARD_NAME VARCHAR(32) NULL,
  ID_CARD_NO   VARCHAR(32) NULL,
  ID_CARD_PIC  BIGINT      NULL,
  MOBILE       VARCHAR(16) NULL,
  TEL          VARCHAR(16) NULL,
  QQ           VARCHAR(16) NULL
);

-- 身份证图片
CREATE TABLE QCM_ID_CARD_PICS (
  ID           BIGINT PRIMARY KEY    AUTO_INCREMENT,
  NAME         VARCHAR(64)  NOT NULL,
  STORAGE_NAME VARCHAR(128) NOT NULL,
  STATUS       BIT(1)       NOT NULL DEFAULT b'0'
);

-- 执照图片
CREATE TABLE QCM_BIZ_LICENSE_PICS (
  ID           BIGINT PRIMARY KEY    AUTO_INCREMENT,
  NAME         VARCHAR(64)  NOT NULL,
  STORAGE_NAME VARCHAR(128) NOT NULL,
  STATUS       BIT(1)       NOT NULL DEFAULT b'0'
);

-- test data
INSERT INTO QCM_ID_CARD_PICS (NAME, STORAGE_NAME, STATUS) VALUES ('420998199010222232.JPG', '6WE63626724727236.JPG', 1);

INSERT INTO QCM_ID_CARD_PICS (NAME, STORAGE_NAME, STATUS)
VALUES ('420998199010222238.JPG', '6WE63626SHRRJ27236.JPG', 1);

INSERT INTO QCM_BIZ_LICENSE_PICS (NAME, STORAGE_NAME, STATUS) VALUES ('62624626.JPG', 'DHEUU3573FHSH.JPG', 1);

INSERT INTO QCM_BIZ_LICENSE_PICS (NAME, STORAGE_NAME, STATUS) VALUES ('636636347.JPG', 'SYYR2626226.JPG', 1);

INSERT INTO QCM_SHOP_OWNERS (NICK_NAME, ID_CARD_NAME, ID_CARD_NO, ID_CARD_PIC, MOBILE, TEL, QQ)
VALUES ('邱处机', '邱振邦', '420998199010222232', 1, '13978223722', '027-87443710', '1482293232');

INSERT INTO QCM_SHOP_OWNERS (NICK_NAME, ID_CARD_NAME, ID_CARD_NO, ID_CARD_PIC, MOBILE, TEL, QQ)
VALUES ('王重阳', '王重阳', '420998199010222238', 2, '13978223728', '027-87443718', '1482293239');

INSERT INTO QCM_SHOPS (NAME, ADDRESS, BIZ_LICENSE_PIC, BIZ_LICENSE_REG_NO, DESCRIPTION, OWNER_ID)
VALUES ('汉西东风雪铁龙', '武汉市汉西市场', 1, '执-A22566-B', '重点客户', 1);

INSERT INTO QCM_SHOPS (NAME, ADDRESS, BIZ_LICENSE_PIC, BIZ_LICENSE_REG_NO, DESCRIPTION, OWNER_ID)
VALUES ('东风日产', '武汉市武昌区杨家湾', 2, '执-A32586-C', '重点客户', 2);
